### ISSUE TITLE
Try to use the most appropriate currency when multiple matches are found for the same amount

### ISSUE THREAD

**Issue by wvega** [smilingrobots/another-unit-converter#11]
This is the first version of the selection rules:

1. If the default currency is among the available options, use the default currency.
2. Use the first available option.

    The list of currencies (in Currencies class) should be created in a way that when multiples currencies use the same symbol, the most common one is listed first. For example, **USD** for **$** and **GBP** for **£**.

**Tasks**

- [x] Return USD for `$`.
- [x] Return GBP for `£`.
- [x] Return EUR for `€`.
