### ISSUE TITLE
Prepare plugin for submission

### ISSUE THREAD

**Issue by wvega** [smilingrobots/another-unit-converter#27]
**Tasks**

- [x] Update plugin information in the main file's [File Headers](https://developer.wordpress.org/plugins/the-basics/header-requirements/). 
- [x] [Create the `readme.txt`](https://github.com/wvega/another-unit-converter/issues/25).
- [x] [Create a website for the plugin](https://github.com/wvega/another-unit-converter/issues/24).
- [ ] Create header image for plugin's page in WordPress.org repository ([example](https://wordpress.org/plugins/jkl-unit-converter/)).

Additional information about how to submit a plugin:

- https://wordpress.org/plugins/developers/
- https://codex.wordpress.org/Writing_a_Plugin
